Shop/Shop.WebUI/Controllers/BasketController.cs
using Shop.Core.Contracts;
using Shop.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.WebUI.Controllers
{
    public class BasketController : Controller
    {

        IBasketService basketService;
        IOrderService orderService;

        public BasketController(IBasketService basketService, IOrderService orderService)
        {
            this.basketService = basketService;
            this.orderService = orderService;
        }

        // GET: Basket
        public ActionResult Index()
        {
            var model = basketService.GetBasketItems(this.HttpContext);
            return View(model);
        }

        public ActionResult AddToBasket(string id)
        {
            basketService.AddBasket(this.HttpContext, id);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromBasket(string id)
        {
            basketService.RemoveFromBasket(this.HttpContext, id);
            return RedirectToAction("Index");
        }

        public PartialViewResult BasketSummary()
        {
            var basketSummary = basketService.GetBasketSummary(this.HttpContext);
            return PartialView(basketSummary);
        }

        public ActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Checkout(Order order)
        {
            var basketItems = basketService.GetBasketItems(this.HttpContext);
            order.OrderStatus = "Order Created";

            //process payment

            order.OrderStatus = "Payment Processed.";
            orderService.CreateOrder(order, basketItems);
            basketService.ClearBasket(this.HttpContext);

            return RedirectToAction("ThankYou", new { OrderId = order.Id });
        }

        public ActionResult ThankYou(string orderId)
        {
            ViewBag.OrderId = orderId;
            return View();
        }
    }
}

Shop/Shop.WebUI/Controllers/HomeController.cs
using Shop.Core.Contracts;
using Shop.Core.Models;
using Shop.Core.View_Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.WebUI.Controllers
{
    public class HomeController : Controller
    {

        IRepository<Product> context;
        IRepository<ProductCategory> productCategories;

        public HomeController(IRepository<Product> productContext, IRepository<ProductCategory> productCategoryContext)
        {
            context = productContext;
            productCategories = productCategoryContext;
        }

        public ActionResult Index(string Category = null)
        {
            List<Product> products;
            List<ProductCategory> categories = productCategories.Collection().ToList();

            if (Category == null)
            {
                products = context.Collection().ToList();
            }
            else
            {
                products = context.Collection().Where(p => p.Category == Category).ToList();
            }

            ProductListViewModel model = new ProductListViewModel();
            model.Products = products;
            model.ProductCategories = categories;

            return View(model);
        }

        public ActionResult Details(string Id)
        {
            Product product = context.Find(Id);
            if(product == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(product);
            }
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Shop/Shop.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Shop/Shop.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Shop/Shop.WebUI/Views/Home/Details.cshtml
@model Shop.Core.Models.Product

@{
    ViewBag.Title = Model.Name + " Details";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

<div>
    <div class="col-md-2">
        <img class="img-responsive" src="~/Content/ProductImages/@Model.Image" />
    </div>
    <div class="col-md-2">
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                $@Html.DisplayFor(model => model.Price)
            </dd>

            <dt></dt>
            <dd><a href="@Url.Action("AddToBasket", "Basket", new { Id=Model.Id })" class="btn btn-default></a></dd>

            <dt></dt>
            <dd>@Html.ActionLink("Back to List", "Index")</dd>
        </dl>
    </div>
</div>

<div class="col-md-12 clearfix" />

Shop/Shop.WebUI/Views/Home/Index.cshtml
@model Shop.Core.View_Model.ProductListViewModel

@{
    ViewBag.Title = "Home Page";
}

<h1>Products</h1>

<div class="col-md-2">
    <h4>Filter By Category</h4>
    <div class="list-group">
        @Html.ActionLink("All", "Index", null, new { @class = Request["Category"] == null? "list-group-item active" : "list-group-item" })
        @foreach (var category in Model.ProductCategories)
        {
            @Html.ActionLink(category.Category, "Index", new { Category = category.Category }, new { @class = Request["Category"] == category.Category ? "list-group-item active" : "list-group-item" })
        }
    </div>
</div>

<div class="col-md-10">
    @foreach (var item in Model.Products)
    {

        <div class="col-md-4" style="height: 450px; padding: 10px; margin: 10px; border: solid thin whitesmoke">
            <div class="col-md-12">
                <img class="img" style="height: 250px" src="~/Content/ProductImages/@item.Image" />
            </div>
            <div class="col-md-12">
                <strong>@Html.ActionLink(item.Name, "Details", new { id = item.Id })</strong>
            </div>
            <div class="col-md-12">
                <p>@item.Description</p>
            </div>
            <div class="col-md-12">
                <h4>@item.Price</h4>
            </div>
            <div>
                <a href="@Url.Action("AddToBasket", "Basket", new { Id=item.Id })" class="btn btn-default">Add to Basket</a>
            </div>
        </div>

    }
</div>

<div class="col-md-12 clearfix" />